[todo_servers]
34.232.51.150 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/admin/.ssh/todo-api-key ansible_become=yes ansible_become_method=sudo ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[todo_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_become=yes
ansible_become_method=sudo
ansible_become_user=root
